
export type PlanType = 'start' | 'professional' | 'redes';
export type SubscriptionStatus = 'active' | 'late' | 'cancelled' | 'trial';
export type TransactionType = 'income' | 'expense';
export type PaymentMethod = 'cash' | 'pix' | 'credit_card' | 'debit_card' | 'credit_split';

export interface SaaSPlan {
  id: PlanType;
  name: string;
  price: number;
  perProfessionalPrice: number;
  features: string[];
  maxProfessionals: number | null; // null for unlimited (or handled by logic)
  isRecommended?: boolean;
}

export interface Coupon {
  id: string;
  code: string;
  discountPercent: number;
  active: boolean;
  uses: number;
}

export interface Review {
  id: string;
  salonId: string;
  clientName: string;
  rating: number; // 1-5
  comment: string;
  date: string;
}

export interface LoyaltyCard {
  salonId: string;
  stamps: number;
  totalRequired: number;
  reward: string;
}

export interface WaitlistEntry {
  id: string;
  salonId: string;
  clientName: string;
  clientPhone: string;
  serviceId: string;
  date: string; // Desired date
}

export interface Service {
  id: string;
  name: string;
  durationMinutes: number;
  price: number;
}

export interface Professional {
  id: string;
  name: string;
  avatarUrl: string;
  commissionRate: number; // Service Commission %
  productCommissionRate: number; // Product Commission %
  password?: string; // Simple auth for MVP
  email: string; // Made mandatory for login
}

export interface Client {
  id: string;
  name: string;
  phone: string;
  birthDate: string; // YYYY-MM-DD
  loyaltyCards?: LoyaltyCard[];
}

export interface Product {
  id: string;
  name: string;
  quantity: number;
  minQuantity: number;
  unit: string; // un, ml, kg
  costPrice?: number;
  // E-commerce fields
  isForSale?: boolean;
  salePrice?: number;
  image?: string;
}

export interface Appointment {
  id: string;
  salonId: string;
  serviceId: string;
  professionalId: string;
  clientName: string;
  clientPhone: string;
  date: string; // ISO string
  status: 'scheduled' | 'completed' | 'cancelled';
  price: number;
  products?: Product[]; // Items bought during booking
}

export interface Transaction {
  id: string;
  description: string;
  amount: number;
  type: TransactionType;
  date: string;
  category: string;
  paymentMethod: PaymentMethod;
  installments?: {
    current: number;
    total: number;
  };
  isAutoGenerated?: boolean; // From appointments or split
}

export interface BlockedPeriod {
  id: string;
  date: string;
  professionalId?: string; // If null/undefined, blocks the whole salon
  reason?: string;
}

export interface Salon {
  id: string;
  createdAt: string; // New field for trial calculation
  name: string;
  ownerEmail?: string;
  password?: string;
  slug: string;
  description: string;
  plan: PlanType;
  services: Service[];
  professionals: Professional[];
  appointments: Appointment[];
  transactions: Transaction[];
  products: Product[];
  address: string;
  coverImage?: string;
  category?: string;
  slotInterval?: number;
  openTime?: string;
  closeTime?: string;
  blockedPeriods?: BlockedPeriod[];
  revenueGoal?: number;
  allowClientCancellation?: boolean;
  aboutUs?: string;
  socials?: {
    instagram?: string;
    facebook?: string;
    whatsapp?: string;
    website?: string;
  };
  gallery?: string[];
  subscriptionStatus: SubscriptionStatus;
  monthlyFee: number;
  nextBillingDate: string;
  appliedCoupon?: string;
  reviews?: Review[];
  waitlist?: WaitlistEntry[];
  loyaltyProgram?: {
    active: boolean;
    totalStamps: number;
    rewardDescription: string;
  };
}

export interface StoreContextType {
  salons: Salon[];
  saasPlans: SaaSPlan[];
  coupons: Coupon[];
  clients: Client[];
  saasRevenueGoal: number; // For SaaS Dashboard
  currentSalonId: string | null;
  setCurrentSalonId: (id: string | null) => void;
  updateSalon: (salon: Salon) => void;
  addAppointment: (salonId: string, appointment: Appointment) => void;
  cancelAppointment: (salonId: string, appointmentId: string) => void; // New Action
  createSalon: (name: string, plan: PlanType, address: string, ownerName?: string, email?: string, password?: string, couponCode?: string) => void;
  addBlockedPeriod: (salonId: string, blockedPeriod: BlockedPeriod) => void;
  saveClient: (client: Client) => void;
  getClientByPhone: (phone: string) => Client | undefined;
  // Financials
  addTransaction: (salonId: string, transaction: Transaction) => void;
  // Inventory
  addProduct: (salonId: string, product: Product) => void;
  updateProduct: (salonId: string, productId: string, quantity: number) => void;
  // SaaS Admin Actions
  updateSaaSPlan: (plan: SaaSPlan) => void;
  addSaaSPlan: (plan: SaaSPlan) => void;
  deleteSaaSPlan: (planId: string) => void;
  createCoupon: (code: string, percent: number) => void;
  toggleSalonStatus: (salonId: string) => void;
  addReview: (salonId: string, review: Review) => void; // Added back
}
